### ISSUE TITLE
Exception 

### ISSUE THREAD

**Issue by xennn** [GhostPack/PSPKIAudit#1] opened 2021-06-18 06:16 UTC
Get-AuditCertificateTemplate: C:\git\PSPKIAudit\Code\Invoke-PKIAudit.ps1:101
Line |
 101 |          $CATemplates = Get-AuditCertificateTemplate @Args
     |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "GetSecurityDescriptor" with "0" argument(s): "Some or all identity references could
     | not be translated."

**Comment by Crypt32** [comment] 2021-06-18 07:21
This is a bug in the underlying library, which is already fixed in sources: https://github.com/PKISolutions/pkix.net/commit/73656c5d4e3dfab9074004d40df2dc466d7fcdcd#diff-c03f25716219c8e87ab3cbb2f2c94261bd961fb79487fa708b7b5822aeb8cff9

the root cause of this is that user account who created this template was deleted from AD. And there is a problem when .NET `CommonObjectSecurity.GetOwner()` throws exception if owner account cannot be resolved, while it handles same case in DACL/SACL. As a temporary workaround (until new PSPKI is released), I can offer compiled updated libraries.

**Comment by xennn** [comment] 2021-06-18 07:43
Thanks for the information. Yes, you are very welcome to make the binaries available.

**Comment by Crypt32** [comment] 2021-06-18 17:17
To all, who face issue with this error, I recommend to update the following files in PowerShell PKI library folder: `$PsModulePath\PSPKI\Library`, where `$PsmodulePath` is PSPKI module installation folder. To get module's installation path, just run the following command:
``` PowerShell
(gmo -li -name pspki).path
```

ZIP with updated and signed DLLs that resolve this issue: [SysadminsLV.PKI.zip](https://github.com/GhostPack/PSPKIAudit/files/6678455/SysadminsLV.PKI.zip)

**Comment by leechristensen** [comment] 2021-06-18 17:41
@Crypt32 Would you be opposed to us bundling that in a release package on this repo until the next version of PSPKI is released?

**Comment by Crypt32** [comment] 2021-06-18 17:56
As long as they are properly attributed, then I wouldn't mind if you host them until next release.

**Comment by leechristensen** [comment] 2021-06-18 18:22
Most definitely. You wouldn't by chance be able to build/sign a Windows PowerShell compatible version would you @Crypt32 ? Only able to load those newer libraries on PowerShell Core right now:
![image](https://user-images.githubusercontent.com/5449193/122602286-6c0c9d00-d027-11eb-8dfd-32ec3ec4374a.png)

**Comment by Crypt32** [comment] 2021-06-18 18:33
It does load for me even on PowerShell 3.0. Make sure that you haven't loaded different versions of this library in the current session.

**Comment by leechristensen** [comment] 2021-06-18 18:46
My fault, after diving it deeper it was mark of the web. Apparently PS core ignores that.... O.o...

**Closed** 2021-06-18 20:26 UTC

**Comment by leechristensen** [comment] 2021-06-18 20:28
New version should be merged.  @Crypt32 please take a look at the top of the readme for the attribution and let us know if you'd like us to change anything. Thanks again for your help!

**Comment by Crypt32** [comment] 2021-06-22 11:50
Looks ok to me.
